# Generated by Django 4.0.6 on 2022-07-24 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_recipe_tag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='tag',
            new_name='tags',
        ),
    ]
